name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CI:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Check formatting
      run: cargo fmt -- --check
    
    - name: Run tests
      run: cargo test 

    - name: Install clippy
      run: rustup component add clippy

    - name: Run clippy
      run: cargo clippy -- -D warnings